image: python:3.4.4

pipelines:
  default:
    - step:
        script:
          - apt-get update
          - apt-get install python3-dev -y
          - chmod +x compile_changetext.sh
          - ./compile_changetext.sh
          - export PYTHONPATH=$PYTHONPATH:.
          - ./test
