name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

      - name: make test
        run: |
          # make test
          # export PYTHONPATH=$PYTHONPATH:.
          # ./test
          pip3 install pytest
          make pytest
