name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: make test
        run: |
          # make test
          # export PYTHONPATH=$PYTHONPATH:.
          # ./test
          pip3 install pytest
          make pytest
